In [1]:
#!pip install h2o

In [2]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np

import pylab as plt
import seaborn as sns

%matplotlib inline

pd.set_option('display.max_columns', None)

In [22]:
rbnb = pd.read_csv('data/train.csv')
rbnb_test = pd.read_csv('data/test.csv')

In [4]:
rbnb.head()

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,0,https://www.airbnb.com/rooms/2842228,20211205213126,2021-12-06,Your little appartment on wheels,A waggon luxurous designed as a hotel room on ...,"Waterland is a beautiful countryside area, wit...",https://a0.muscache.com/pictures/cc2aa51a-3c11...,3040748,https://www.airbnb.com/users/show/3040748,Henk,2012-07-24,"Amsterdam, North Holland, The Netherlands","Living in the countryside, just near Amsterdam...",within a few hours,100%,75%,f,https://a0.muscache.com/im/users/3040748/profi...,https://a0.muscache.com/im/users/3040748/profi...,NaN,13,13,"['email', 'phone', 'reviews', 'jumio', 'offlin...",t,t,"Amsterdam, North Holland, Netherlands",Noord-Oost,NaN,52.39508,4.99186,Private room in farm stay,Private room,3,NaN,1.5 shared baths,1.0,NaN,"[""First aid kit"", ""Free parking on premises"", ...",87.0,2,1125,2.0,2.0,1125.0,1125.0,2.0,1125.0,NaN,t,0,0,0,249,2021-12-06,81,0,0,2014-08-03,2019-06-15,4.62,4.56,4.29,4.57,4.75,4.69,4.49,0363 2A6D 7C09 877D 715F,f,10,0,10,0,0.91
1,1,https://www.airbnb.com/rooms/41236669,20211205213126,2021-12-06,Spacious 4p city center apartment (2 bedrooms!),Are you looking for a perfect place to stay in...,Our home is located in the Plantagebuurt. A un...,https://a0.muscache.com/pictures/5f33bf5a-399c...,34773624,https://www.airbnb.com/users/show/34773624,Julie,2015-06-01,"Amsterdam, Noord-Holland, Netherlands",NaN,NaN,NaN,NaN,f,https://a0.muscache.com/im/pictures/user/a5da3...,https://a0.muscache.com/im/pictures/user/a5da3...,Weesperbuurt en Plantage,0,0,"['email', 'phone', 'reviews']",t,f,"Amsterdam, Noord-Holland, Netherlands",Centrum-Oost,NaN,52.36371,4.90745,Entire rental unit,Entire home/apt,4,NaN,1 bath,2.0,2.0,"[""Hot water kettle"", ""Pocket wifi"", ""Stove"", ""...",250.0,2,1125,2.0,2.0,1125.0,1125.0,2.0,1125.0,NaN,t,3,3,3,3,2021-12-06,9,4,1,2020-01-26,2021-09-05,5.00,5.00,5.00,4.89,5.00,5.00,4.89,0363 BD0E 9934 ACCA D3DE,f,1,1,0,0,0.40
2,2,https://www.airbnb.com/rooms/27240740,20211205213126,2021-12-06,SWEETS hotel Theophile de Bockbrug,Comfortable bridge house on the doorstep of Am...,"The neighbourhood has a quiet, village-like fe...",https://a0.muscache.com/pictures/b1145dd1-e485...,203731852,https://www.airbnb.com/users/show/203731852,SWEETS Hotel,2018-07-20,"Wassenaar, South Holland, Netherlands",SWEETS hotel is a one-of-a-kind hotel located ...,within an hour,100%,97%,t,https://a0.muscache.com/im/pictures/user/492cd...,https://a0.muscache.com/im/pictures/user/492cd...,Hoofddorppleinbuurt,20,20,"['email', 'phone']",t,t,"Amsterdam, Noord-Holland, Netherlands",Zuid,NaN,52.35482,4.85329,Room in serviced apartment,Hotel room,2,NaN,1 private bath,1.0,1.0,"[""Air conditioning"", ""First aid kit"", ""Hangers...",151.0,1,1125,1.0,1.0,99.0,99.0,1.0,99.0,NaN,t,25,55,85,267,2021-12-06,47,3,1,2018-11-09,2020-03-07,4.79,4.83,4.91,4.62,4.87,4.87,4.40,Exempt,t,20,4,0,0,1.25
3,3,https://www.airbnb.com/rooms/33326302,20211205213126,2021-12-05,Lovely home near Vondelpark: great for couples!,"In het gezellige Amsterdamse Oud-West, vind je...",Oud-West is een van de gezelligste wijken in A...,https://a0.muscache.com/pictures/75f8ae17-eeb8...,68783888,https://www.airbnb.com/users/show/68783888,Lotte,2016-04-25,"Amsterdam, North Holland, Netherlands",NaN,within an hour,100%,67%,f,https://a0.muscache.com/im/pictures/user/a4d0e...,https://a0.muscache.com/im/pictures/user/a4d0e...,Oud-West,1,1,"['email', 'phone', 'facebook']",t,f,"Amsterdam, Noord-Holland, Netherlands",De Baarsjes - Oud-West,NaN,52.36446,4.85972,Entire rental unit,Entire home/apt,2,NaN,1.5 baths,1.0,1.0,"[""Hair dryer"", ""Stove"", ""Dishes and silverware...",139.0,2,30,2.0,2.0,1125.0,1125.0,2.0,1125.0,NaN,t,0,0,0,0,2021-12-05,10,3,0,2019-04-22,2019-11-10,5.00,5.00,4.80,5.00,5.00,4.90,4.70,0363 7E52 3D3D 6AB1 3C72,f,1,1,0,0,0.31
4,4,https://www.airbnb.com/rooms/969862,20211205213126,2021-12-06,Living in a houseboat on the water,<b>The space</b><br />The apartment is a part ...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,5297940,https://www.airbnb.com/users/show/5297940,Helga,2013-03-03,"Amsterdam, North Holland, The Netherlands",Helga had the Austrian nationality before she ...,within a few hours,100%,75%,t,https://a0.muscache.com/im/users/5297940/profi...,https://a0.muscache.com/im/users/5297940/profi...,Oud-Zuid,1,1,"['email', 'phone', 'reviews', 'manual_offline'...",t,t,NaN,Zuid,NaN,52.34176,4.84782,Private room in rental unit,Private room,2,NaN,1.5 baths,1.0,2.0,"[""Hair dryer"", ""Dishes and silverware"", ""Ether...",95.0,2,7,2.0,2.0,7.0,7.0,2.0,7.0,NaN,t,18,48,78,349,2021-12-06,166,1,0,2014-04-08,2019-08-26,4.67,4.76,4.81,4.95,4.89,4.49,4.57,0363 77F9 4DBC 2E88 41C2,f,1,0,1,0,1.78

In [5]:
rbnb.shape

(4167, 74)

In [6]:
rbnb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4167 entries, 0 to 4166
Data columns (total 74 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            4167 non-null   int64
 1   listing_url                                   4167 non-null   object
 2   scrape_id                                     4167 non-null   int64
 3   last_scraped                                  4167 non-null   object
 4   name                                          4167 non-null   object
 5   description                                   4159 non-null   object
 6   neighborhood_overview                         3004 non-null   object
 7   picture_url                                   4167 non-null   object
 8   host_id                                       4167 non-null   int64
 9   host_url                                      4167 non-null   object
 10  host_name                                     4167 non-null   object
 11  host_since                                    4167 non-null   object
 12  host_location                                 4155 non-null   object
 13  host_about                                    2655 non-null   object
 14  host_response_time                            2754 non-null   object
 15  host_response_rate                            2754 non-null   object
 16  host_acceptance_rate                          3075 non-null   object
 17  host_is_superhost                             4167 non-null   object
 18  host_thumbnail_url                            4167 non-null   object
 19  host_picture_url                              4167 non-null   object
 20  host_neighbourhood                            2381 non-null   object
 21  host_listings_count                           4167 non-null   int64
 22  host_total_listings_count                     4167 non-null   int64
 23  host_verifications                            4167 non-null   object
 24  host_has_profile_pic                          4167 non-null   object
 25  host_identity_verified                        4167 non-null   object
 26  neighbourhood                                 3004 non-null   object
 27  neighbourhood_cleansed                        4167 non-null   object
 28  neighbourhood_group_cleansed                  0 non-null      float64
 29  latitude                                      4167 non-null   float64
 30  longitude                                     4167 non-null   float64
 31  property_type                                 4167 non-null   object
 32  room_type                                     4167 non-null   object
 33  accommodates                                  4167 non-null   int64
 34  bathrooms                                     0 non-null      float64
 35  bathrooms_text                                4159 non-null   object
 36  bedrooms                                      3914 non-null   float64
 37  beds                                          3993 non-null   float64
 38  amenities                                     4167 non-null   object
 39  price                                         4167 non-null   float64
 40  minimum_nights                                4167 non-null   int64
 41  maximum_nights                                4167 non-null   int64
 42  minimum_minimum_nights                        4166 non-null   float64
 43  maximum_minimum_nights                        4166 non-null   float64
 44  minimum_maximum_nights                        4166 non-null   float64
 45  maximum_maximum_nights                        4166 non-null   float64
 46  minimum_nights_avg_ntm                        4166 non-null   float64
 47  maximum_nights_avg_ntm                        4166 non-null   float64
 48  calendar_updated                              0 non-null      float64
 49  has_availability                              4167 non-null   object
 50  availability_30                               4167 non-null   int64
 51  availability_60                               4167 non-null   int64
 52  availability_90                               4167 non-null   int64
 53  availability_365                              4167 non-null   int64
 54  calendar_last_scraped                         4167 non-null   object
 55  number_of_reviews                             4167 non-null   int64
 56  number_of_reviews_ltm                         4167 non-null   int64
 57  number_of_reviews_l30d                        4167 non-null   int64
 58  first_review                                  3790 non-null   object
 59  last_review                                   3790 non-null   object
 60  review_scores_rating                          3790 non-null   float64
 61  review_scores_accuracy                        3782 non-null   float64
 62  review_scores_cleanliness                     3782 non-null   float64
 63  review_scores_checkin                         3782 non-null   float64
 64  review_scores_communication                   3782 non-null   float64
 65  review_scores_location                        3782 non-null   float64
 66  review_scores_value                           3782 non-null   float64
 67  license                                       4135 non-null   object
 68  instant_bookable                              4167 non-null   object
 69  calculated_host_listings_count                4167 non-null   int64
 70  calculated_host_listings_count_entire_homes   4167 non-null   int64
 71  calculated_host_listings_count_private_rooms  4167 non-null   int64
 72  calculated_host_listings_count_shared_rooms   4167 non-null   int64
 73  reviews_per_month                             3790 non-null   float64
dtypes: float64(22), int64(19), object(33)
memory usage: 2.4+ MB

In [7]:
rbnb.describe().T

,count,mean,std,min,25%,50%,75%,max
id,4167.0,2.083000e+03,1.203054e+03,0.000000e+00,1.041500e+03,2.083000e+03,3.124500e+03,4.166000e+03
scrape_id,4167.0,2.021121e+13,3.906719e-03,2.021121e+13,2.021121e+13,2.021121e+13,2.021121e+13,2.021121e+13
host_id,4167.0,8.968890e+07,1.158584e+08,3.159000e+03,9.002030e+06,3.133220e+07,1.354875e+08,4.346341e+08
host_listings_count,4167.0,2.488601e+00,1.450804e+01,0.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,7.180000e+02
host_total_listings_count,4167.0,2.488601e+00,1.450804e+01,0.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,7.180000e+02
neighbourhood_group_cleansed,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
latitude,4167.0,5.236691e+01,1.683493e-02,5.229103e+01,5.235666e+01,5.236659e+01,5.237655e+01,5.242476e+01
longitude,4167.0,4.891435e+00,3.617564e-02,4.753510e+00,4.869430e+00,4.888790e+00,4.908985e+00,5.026430e+00
accommodates,4167.0,2.941205e+00,1.464789e+00,0.000000e+00,2.000000e+00,2.000000e+00,4.000000e+00,1.600000e+01
bathrooms,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bedrooms,3914.0,1.577414e+00,9.168111e-01,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,1.000000e+01
beds,3993.0,1.956424e+00,1.640881e+00,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,3.300000e+01
price,4167.0,1.686770e+02,1.806586e+02,0.000000e+00,9.800000e+01,1.380000e+02,2.000000e+02,6.477000e+03
minimum_nights,4167.0,3.670746e+00,2.245592e+01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,1.001000e+03
maximum_nights,4167.0,5.354471e+02,5.259252e+02,1.000000e+00,2.500000e+01,3.650000e+02,1.125000e+03,1.825000e+03
minimum_minimum_nights,4166.0,3.596495e+00,2.245493e+01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,1.001000e+03
maximum_minimum_nights,4166.0,4.113538e+00,2.269528e+01,1.000000e+00,2.000000e+00,3.000000e+00,4.000000e+00,1.001000e+03
minimum_maximum_nights,4166.0,6.664698e+02,5.243284e+02,1.000000e+00,3.000000e+01,1.125000e+03,1.125000e+03,1.825000e+03
maximum_maximum_nights,4166.0,5.161639e+05,3.327132e+07,1.000000e+00,3.000000e+01,1.125000e+03,1.125000e+03,2.147484e+09
minimum_nights_avg_ntm,4166.0,3.799136e+00,2.251351e+01,1.000000e+00,2.000000e+00,2.100000e+00,3.000000e+00,1.001000e+03
maximum_nights_avg_ntm,4166.0,5.149907e+05,3.319605e+07,1.000000e+00,3.000000e+01,1.125000e+03,1.125000e+03,2.142625e+09
calendar_updated,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
availability_30,4167.0,7.869210e+00,9.553871e+00,0.000000e+00,0.000000e+00,3.000000e+00,1.500000e+01,3.000000e+01
availability_60,4167.0,1.851788e+01,2.084260e+01,0.000000e+00,0.000000e+00,9.000000e+00,3.600000e+01,6.000000e+01
availability_90,4167.0,2.962203e+01,3.273095e+01,0.000000e+00,0.000000e+00,1.300000e+01,6.300000e+01,9.000000e+01
availability_365,4167.0,1.065515e+02,1.291552e+02,0.000000e+00,0.000000e+00,3.400000e+01,2.085000e+02,3.650000e+02
number_of_reviews,4167.0,4.894576e+01,8.933245e+01,0.000000e+00,5.000000e+00,1.700000e+01,4.700000e+01,9.010000e+02
number_of_reviews_ltm,4167.0,6.310535e+00,1.956165e+01,0.000000e+00,0.000000e+00,1.000000e+00,6.000000e+00,5.970000e+02
number_of_reviews_l30d,4167.0,8.341733e-01,2.331628e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,6.100000e+01
review_scores_rating,3790.0,4.794061e+00,3.512184e-01,0.000000e+00,4.730000e+00,4.880000e+00,5.000000e+00,5.000000e+00
review_scores_accuracy,3782.0,4.836227e+00,2.636410e-01,1.000000e+00,4.780000e+00,4.910000e+00,5.000000e+00,5.000000e+00
review_scores_cleanliness,3782.0,4.751623e+00,3.293391e-01,1.000000e+00,4.670000e+00,4.850000e+00,4.970000e+00,5.000000e+00
review_scores_checkin,3782.0,4.875354e+00,2.537162e-01,1.000000e+00,4.852500e+00,4.950000e+00,5.000000e+00,5.000000e+00
review_scores_communication,3782.0,4.882110e+00,2.589936e-01,1.000000e+00,4.870000e+00,4.960000e+00,5.000000e+00,5.000000e+00
review_scores_location,3782.0,4.782078e+00,2.494620e-01,1.000000e+00,4.670000e+00,4.845000e+00,4.970000e+00,5.000000e+00
review_scores_value,3782.0,4.643794e+00,3.083659e-01,1.000000e+00,4.530000e+00,4.690000e+00,4.810000e+00,5.000000e+00
calculated_host_listings_count,4167.0,2.155508e+00,3.094729e+00,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,2.200000e+01
calculated_host_listings_count_entire_homes,4167.0,1.090473e+00,1.913322e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,2.200000e+01
calculated_host_listings_count_private_rooms,4167.0,9.347252e-01,2.325021e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,2.100000e+01
calculated_host_listings_count_shared_rooms,4167.0,1.655868e-02,2.077804e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00
reviews_per_month,3790.0,1.452625e+00,2.816455e+00,1.000000e-02,3.100000e-01,6.800000e-01,1.700000e+00,9.589000e+01

# H2O

In [8]:
import h2o
from h2o.automl import H2OAutoML

In [9]:
# inicializamos el modelo h2o

h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321 ..... not found.
Attempting to start a local H2O server...
; Java HotSpot(TM) 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)
  Starting server from C:\Users\usuario\.conda\envs\clase\Lib\site-packages\h2o\backend\bin\h2o.jar
  Ice root: C:\Users\usuario\AppData\Local\Temp\tmphf43n8le
  JVM stdout: C:\Users\usuario\AppData\Local\Temp\tmphf43n8le\h2o_usuario_started_from_python.out
  JVM stderr: C:\Users\usuario\AppData\Local\Temp\tmphf43n8le\h2o_usuario_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  ------------------------------
H2O_cluster_uptime:         01 secs
H2O_cluster_timezone:       Europe/Madrid
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.36.1.1
H2O_cluster_version_age:    20 days
H2O_cluster_name:           H2O_from_python_usuario_me4kxn
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    2.924 Gb
H2O_cluster_total_cores:    8
H2O_cluster_allowed_cores:  8
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
Python_version:             3.9.7 final
--------------------------  ------------------------------

In [10]:

from sklearn.model_selection import train_test_split as tts


train, test = tts(rbnb, test_size=.2, random_state=42)

train.shape, test.shape

((3333, 74), (834, 74))

In [11]:
h2train=h2o.H2OFrame(train)
h2test=h2o.H2OFrame(test)

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

In [12]:
X=[c for c in h2train.columns if c!='price']

y='price'

In [13]:
# inicia auto-machine-learning

automl=H2OAutoML(max_models=50,
                 seed=42,   # random_state
                 max_runtime_secs=300,
                 sort_metric='RMSE')

In [14]:
# entrena

automl.train(x=X,
             y=y,
             training_frame=h2train)

AutoML progress: |
21:39:13.138: AutoML: XGBoost is not available; skipping it.
21:39:13.189: _train param, Dropping bad and constant columns: [amenities, picture_url, neighbourhood_group_cleansed, calendar_updated, listing_url, name, description, bathrooms, scrape_id]

████████
21:39:45.536: GLM_1_AutoML_1_20220503_213913 [GLM def_1] failed: DistributedException from /127.0.0.1:54321: 'Java heap space', caused by java.lang.OutOfMemoryError: Java heap space
21:39:45.656: _train param, Dropping bad and constant columns: [amenities, picture_url, neighbourhood_group_cleansed, calendar_updated, listing_url, name, description, bathrooms, scrape_id]

█
21:39:50.640: _train param, Dropping bad and constant columns: [amenities, picture_url, neighbourhood_group_cleansed, calendar_updated, listing_url, name, description, bathrooms, scrape_id]

██████████
21:40:41.952: _train param, Dropping bad and constant columns: [amenities, picture_url, neighbourhood_group_cleansed, calendar_updated, listing_url, name, description, bathrooms, scrape_id]

███
21:40:54.769: _train param, Dropping bad and constant columns: [amenities, picture_url, neighbourhood_group_cleansed, calendar_updated, listing_url, name, description, bathrooms, scrape_id]

███
21:41:09.574: _train param, Dropping bad and constant columns: [amenities, picture_url, neighbourhood_group_cleansed, calendar_updated, listing_url, name, description, bathrooms, scrape_id]

███
21:41:25.513: _train param, Dropping bad and constant columns: [amenities, picture_url, neighbourhood_group_cleansed, calendar_updated, listing_url, name, description, bathrooms, scrape_id]

█████████████
21:42:28.235: _train param, Dropping bad and constant columns: [amenities, picture_url, neighbourhood_group_cleansed, calendar_updated, listing_url, name, description, bathrooms, scrape_id]

█
21:42:33.83: _train param, Dropping bad and constant columns: [amenities, picture_url, neighbourhood_group_cleansed, calendar_updated, listing_url, name, description, bathrooms, scrape_id]

█████████████████████| (done) 100%
Model Details
=============
H2OGradientBoostingEstimator :  Gradient Boosting Machine
Model Key:  GBM_5_AutoML_1_20220503_213913


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,62.0,62.0,60915.0,6.0,6.0,6.0,25.0,63.0,46.935482

ModelMetricsRegression: gbm
** Reported on train data. **

MSE: 1129.636224245388
RMSE: 33.61006135438297
MAE: 22.851439940975908
RMSLE: 0.24938959792540794
Mean Residual Deviance: 1129.636224245388

ModelMetricsRegression: gbm
** Reported on cross-validation data. **

MSE: 9481.229312619731
RMSE: 97.37160424178977
MAE: 50.34154293943399
RMSLE: NaN
Mean Residual Deviance: 9481.229312619731

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,mae,49.971226,1.505475,50.103844,50.446774,50.132267,47.525032,51.648212
1,mean_residual_deviance,9599.678000,1724.088000,8462.748000,8648.253000,11215.213000,7969.221000,11702.951000
2,mse,9599.678000,1724.088000,8462.748000,8648.253000,11215.213000,7969.221000,11702.951000
3,r2,0.495507,0.380268,0.880405,0.344296,0.019826,0.892049,0.340958
4,residual_deviance,9599.678000,1724.088000,8462.748000,8648.253000,11215.213000,7969.221000,11702.951000
5,rmse,97.668350,8.701325,91.993195,92.995990,105.901900,89.270490,108.180180
6,rmsle,0.405098,0.030909,NaN,0.375265,0.391444,0.406295,0.447386

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2022-05-03 21:42:32,3.835 sec,0.0,193.467206,80.227498,37429.559685
1,,2022-05-03 21:42:32,3.941 sec,5.0,135.433738,61.924184,18342.297273
2,,2022-05-03 21:42:32,4.024 sec,10.0,97.307366,50.877723,9468.723416
3,,2022-05-03 21:42:32,4.122 sec,15.0,77.756957,44.424621,6046.144424
4,,2022-05-03 21:42:32,4.181 sec,20.0,63.489930,39.715187,4030.971234
5,,2022-05-03 21:42:32,4.295 sec,25.0,54.165336,36.185145,2933.883653
6,,2022-05-03 21:42:32,4.390 sec,30.0,49.153908,33.301696,2416.106656
7,,2022-05-03 21:42:32,4.451 sec,35.0,45.490872,30.776134,2069.419426
8,,2022-05-03 21:42:32,4.527 sec,40.0,42.356263,28.780631,1794.052977
9,,2022-05-03 21:42:32,4.583 sec,45.0,39.862837,27.046024,1589.045788
10,,2022-05-03 21:42:32,4.632 sec,50.0,37.940547,25.579803,1439.485085
11,,2022-05-03 21:42:32,4.687 sec,55.0,36.024003,24.340899,1297.728777
12,,2022-05-03 21:42:32,4.737 sec,60.0,34.423613,23.289486,1184.985098
13,,2022-05-03 21:42:33,4.767 sec,62.0,33.610061,22.851440,1129.636224

Variable Importances:

,variable,relative_importance,scaled_importance,percentage
0,host_neighbourhood,114980112.0,1.000000,0.197864
1,property_type,106546952.0,0.926655,0.183352
2,calculated_host_listings_count_private_rooms,53919128.0,0.468943,0.092787
3,neighbourhood_cleansed,41548060.0,0.361350,0.071498
4,accommodates,38347488.0,0.333514,0.065991
5,host_verifications,30356480.0,0.264015,0.052239
6,license,21622782.0,0.188057,0.037210
7,bedrooms,20475400.0,0.178078,0.035235
8,host_since,20156300.0,0.175302,0.034686
9,host_acceptance_rate,14325252.0,0.124589,0.024652
10,bathrooms_text,13954254.0,0.121362,0.024013
11,availability_365,12760649.0,0.110981,0.021959
12,host_location,10415753.0,0.090587,0.017924
13,beds,9776670.0,0.085029,0.016824
14,host_listings_count,7843908.0,0.068220,0.013498
15,availability_30,7401724.5,0.064374,0.012737
16,host_response_rate,6412283.5,0.055769,0.011035
17,availability_90,5906287.5,0.051368,0.010164
18,calculated_host_listings_count,4606321.5,0.040062,0.007927
19,availability_60,3621716.5,0.031499,0.006232

See the whole table with table.as_data_frame()

In [15]:
print('[INFO] Leader board:')

leader_board=automl.leaderboard

leader_board.head()

[INFO] Leader board:

model_id,rmse,mse,mae,rmsle,mean_residual_deviance
GBM_5_AutoML_1_20220503_213913,97.3716,9481.23,50.3415,nan,9481.23
GBM_2_AutoML_1_20220503_213913,100.893,10179.3,54.5709,nan,10179.3
GBM_3_AutoML_1_20220503_213913,101.091,10219.3,54.5379,nan,10219.3
GBM_4_AutoML_1_20220503_213913,101.222,10245.8,53.4855,nan,10245.8
GBM_grid_1_AutoML_1_20220503_213913_model_2,102.36,10477.7,55.4282,nan,10477.7
GBM_grid_1_AutoML_1_20220503_213913_model_1,102.703,10548,53.5857,nan,10548
GBM_grid_1_AutoML_1_20220503_213913_model_3,105.491,11128.3,53.9412,nan,11128.3
DRF_1_AutoML_1_20220503_213913,116.561,13586.4,51.8256,0.419024,13586.4
XRT_1_AutoML_1_20220503_213913,147.651,21800.8,59.6025,0.461184,21800.8
GBM_1_AutoML_1_20220503_213913,173.673,30162.3,57.0676,nan,30162.3

In [16]:
# prediciones del lider

y_pred=automl.leader.predict(h2test)

gbm prediction progress: |███████████████████████████████████████████████████████| (done) 100%

In [17]:
y_pred

predict
108.615
195.482
120.503
158.714
129.075
79.9856
166.736
108.484
70.4671
153.214

In [18]:
# y_pred_test = h2o.as_list(y_pred, use_pandas=False) # Cambiara h2o a una lista

# y_test = test.price # y_test del data train

In [19]:
# Para testear la precisión de mi modelo

'''from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred_test)'''

'from sklearn.metrics import accuracy_score\n\naccuracy_score(y_test, y_pred_test)'

In [46]:
h2_real_test=h2o.H2OFrame(rbnb_test)

y_pred_test = automl.leader.predict(h2_real_test)

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
gbm prediction progress: |███████████████████████████████████████████████████████| (done) 100%

In [47]:
submission = h2o.as_list(y_pred_test)

In [48]:
rbnb_test_y = rbnb_test.id

In [30]:
rbnb_test_y

0          0
1          1
2          2
3          3
4          4
        ...
1384    1384
1385    1385
1386    1386
1387    1387
1388    1388
Name: id, Length: 1389, dtype: int64

In [50]:
submission['id'] = rbnb_test_y

In [55]:
submission = submission.rename(columns={'predict': 'price'})

In [61]:
submission

           price    id
0     109.217735     0
1      56.440378     1
2     114.819322     2
3     121.563979     3
4     125.568971     4
...          ...   ...
1384   58.753376  1384
1385  133.445567  1385
1386  184.855206  1386
1387  137.479047  1387
1388  120.287302  1388

[1389 rows x 2 columns]

In [59]:
submission.to_csv('data/submission.csv', sep=',', index=False)